backend/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf.urls.static import static
import backend.settings as settings
from django.views.generic.base import RedirectView


urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("api/", include("conferences.urls")),
    path("", include("pages.urls")),
]

pages/urls.py
from operator import index

from conferences.views.entrada import EntradaView
from django.conf.urls import include, url
from django.contrib.auth.views import PasswordChangeDoneView, PasswordChangeView
from django.urls import path, register_converter
from my_addons.utils import DateConverter

from pages.views.accounts.account_profile_detail import ProfileDetailView
from pages.views.accounts.account_profile_edit import ProfileUpdateView
from pages.views.accounts.account_registration import AccountRegistrationView
from pages.views.accounts.account_speaker_profile_edit import SpeakeProfileUpdateView
from pages.views.agenda.agenda import AgendaPageView
from pages.views.agenda.agenda_day import AgendaDayPageView
from pages.views.event_schedule.download_ics_event import download_talk_ics_file
from pages.views.event_schedule.speaker_profile import SpeakerProfileView
from pages.views.event_schedule.speakers import EventSpeakersPageView
from pages.views.event_schedule.talk_detail import TalkDetailView
from pages.views.event_schedule.talk_schedule import TalkScheduleView
from pages.views.event_schedule.talks import (
    EventKeynotePageView,
    EventSprintPageView,
    EventTalksPageView,
    EventWorkshopPageView,
)
from pages.views.event_schedule.talks_schedule_basic import (
    EventTalksScheduleBasicPageView,
)
from pages.views.event_schedule.workshop_attendance import (
    WorkshopAttendanceView,
    UpdateAttendanceView,
)
from pages.views.events.collaborators import (
    AcademicCommitteeView,
    CollaboratorDetailView,
    CollaboratorsView,
    ProceedingsView,
)
from pages.views.events.event_registration import EventRegistrationView
from pages.views.events.event_registration_list import EventRegistrationListView
from pages.views.events.event_talk_preview import TalkPreviewView
from pages.views.events.event_talk_registration import (
    EventTalkRegistrationSuccesfull,
    EventTalkRegistrationView,
)
from pages.views.events.event_talk_resource_create import TalkResourceCreateView
from pages.views.events.event_talk_resource_create_by_type import (
    TalkResourceCreateByTypeView,
)
from pages.views.events.event_talk_resource_delete import EventTalkResourceDeleteView
from pages.views.events.event_talk_resource_update import EventTalkResourceUpdateView
from pages.views.events.event_talk_update import EventTalkUpdateView
from pages.views.events.talk_registration import (
    TalkRegistration,
    TalkRegistrationAdd,
    TalkRegistrationDel,
)
from pages.views.home import HomePageView
from pages.views.location import LocationPageView
from pages.views.not_implemented import NotImplementedView
from pages.views.playground import PlaygroundView
from pages.views.sponsors import SponsorListView
from pages.views.static_page import render_static_page
from pages.views.twitter_news import TwitterNewsView

register_converter(DateConverter, "yyyy")

# Create your views here.
urlpatterns = [
    path("accounts/profile/", ProfileDetailView.as_view(), name="profile"),
    path(
        "accounts/registration/", AccountRegistrationView.as_view(), name="registration"
    ),
    path("accounts/profile/edit/", ProfileUpdateView.as_view(), name="profile_edit"),
    path(
        "accounts/speaker/edit/",
        SpeakeProfileUpdateView.as_view(),
        name="speaker_profile_edit",
    ),
    path(
        "accounts/change-password/",
        PasswordChangeView.as_view(template_name="account/change-password.html"),
        name="change_password",
    ),
    path(
        "accounts/change-password/done/",
        PasswordChangeDoneView.as_view(
            template_name="account/change-password-done.html"
        ),
        name="password_change_done",
    ),
    path(
        "events/availables",
        EventRegistrationListView.as_view(),
        name="available_events",
    ),
    path(
        "events/registration/<int:pk>/",
        EventRegistrationView.as_view(),
        name="event_registration",
    ),
    path(
        "events/<int:pk>/talks/talk-registration",
        EventTalkRegistrationView.as_view(),
        name="event-talk-registration",
    ),
    path(
        "events/talks/talk-registration-succesfull/<int:pk>/",
        EventTalkRegistrationSuccesfull.as_view(),
        name="event-talk-registration-succesfull",
    ),
    path("events/talks/", EventTalksPageView.as_view(), name="talks"),
    path("events/sprints/", EventSprintPageView.as_view(), name="sprints"),
    path("events/workshops/", EventWorkshopPageView.as_view(), name="workshops"),
    path("events/keynotes/", EventKeynotePageView.as_view(), name="keynotes"),
    path("event/talks/<int:pk>/", EventTalksPageView.as_view(), name="event_talks"),
    path("talks/detail/<int:pk>/", TalkDetailView.as_view(), name="talk_detail"),
    path("talks/preview/<int:pk>/", TalkPreviewView.as_view(), name="talk_preview"),
    path("talks/edit/<int:pk>/", EventTalkUpdateView.as_view(), name="talk_edit"),
    path(
        "talks/add-resource/<int:pk>/",
        TalkResourceCreateView.as_view(),
        name="talk_resource_type",
    ),
    path(
        "talks/add-resource/<int:pk>/<str:type>/",
        TalkResourceCreateByTypeView.as_view(),
        name="talk_resource_create",
    ),
    path(
        "talks/update-resource/<int:pk>/",
        EventTalkResourceUpdateView.as_view(),
        name="talk_resource_update",
    ),
    path(
        "talks/delete-resource/<int:pk>/",
        EventTalkResourceDeleteView.as_view(),
        name="talk_resource_delete",
    ),
    path(
        "talks/download-event-calendar/<int:pk>/",
        download_talk_ics_file,
        name="download-ics-event",
    ),
    path("location", LocationPageView.as_view(), name="location"),
    path("noticias", TwitterNewsView.as_view(), name="twitter_news"),
    path("speakers", EventSpeakersPageView.as_view(), name="speakers"),
    path("speakers/<int:pk>/", SpeakerProfileView.as_view(), name="speaker_profile"),
    path("sponsors", SponsorListView.as_view(), name="sponsors"),
    path("pages/<slug:slug>/", render_static_page, name="static_page"),
    path("playground/", PlaygroundView.as_view(), name="playground"),
    path(
        "talks/talk-registration/", TalkRegistration.as_view(), name="talk-registration"
    ),
    path(
        "talks/talk-registration/add/<int:pk>/",
        TalkRegistrationAdd,
        name="talk-registration-add",
    ),
    path(
        "talks/talk-registration/delete/<int:pk>/",
        TalkRegistrationDel,
        name="talk-registration-del",
    ),
    path(
        "event-schedule/",
        EventTalksScheduleBasicPageView.as_view(),
        name="talks-schedule",
    ),
    path("schedule/", EventTalksScheduleBasicPageView.as_view(), name="talks-schedule"),
    path("talks/schedule/", TalkScheduleView.as_view(), name="event-talk-schedule"),
    path(
        "talks/attendance/<int:talk_id>/",
        WorkshopAttendanceView.as_view(),
        name="workshop-attendance",
    ),
    path(
        "talks/attendance/update/<int:talk_room_id>/<int:profile_id>/",
        UpdateAttendanceView.as_view(),
        name="workshop-attendance-update",
    ),
    path(
        "talks/schedule/<yyyy:date>/",
        TalkScheduleView.as_view(),
        name="event-talk-schedule",
    ),
    # Agenda
    path("agenda/", AgendaPageView.as_view(), name="talks-agenda"),
    path("agenda_day/<int:day>/", AgendaDayPageView.as_view(), name="talks-agenda-day"),
    path("entrada/", EntradaView, name="entrada"),
    path("colaboradores", CollaboratorsView.as_view(), name="collaborators"),
    path("actas", ProceedingsView.as_view(), name="proceedings"),
    path(
        "comite-academico", AcademicCommitteeView.as_view(), name="academic-committee"
    ),
    path(
        "colaboradores/<int:pk>/",
        CollaboratorDetailView.as_view(),
        name="collaborator_profile",
    ),
    path("", HomePageView.as_view(), name="home"),
    path("not-found/", NotImplementedView.as_view(), name="not_found"),
]

conferences/models/event_registrations.py
from django.db import models


class EventRegistration(models.Model):
    event = models.ForeignKey(
        "Event",
        related_name="registrations",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        default=None,
    )
    profile = models.ForeignKey(
        "Profile", related_name="registrations", on_delete=models.CASCADE
    )
    is_speaker = models.BooleanField(default=False)
    is_organizer = models.BooleanField(default=False)
    asked_for_a_grant = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "event_registrations"
        verbose_name = "Event Registration"
        verbose_name_plural = "Events Registrations"

    def __str__(self):
        return self.event.name

conferences/models/talk_registration.py
import profile
from django.db import models


class TalkRegistration(models.Model):
    talk = models.ForeignKey(
        "Talk", related_name="talks_registrations", on_delete=models.CASCADE
    )
    profile = models.ForeignKey(
        "Profile", related_name="talks_registrations_profile", on_delete=models.CASCADE
    )

    class Meta:
        db_table = "talk_registrations"
        verbose_name = "Talk Registration"
        verbose_name_plural = "Talk Registrations"

    def __str__(self):
        return f"{self.talk} - {self.profile.full_name}"

conferences/models/talks.py
from django.db import models


class Talk(models.Model):
    TALKS_TYPE = (
        ("talk", "Charla"),
        ("workshop", "Workshop/Taller"),
        # ("tutorial", "Tutorial"),
        ("keynote", "Keynote/Charla magistral"),
        ("lightning_talk", "Lightning Talk"),
        ("sprints", "Sprints"),
        ("open_space", "Open Space"),
        ("panel", "Panel"),
        # ("other", "Other"),
    )

    STATUS = (
        ("draft", "draft"),
        ("in_review", "in_review"),
        ("published", "published"),
        ("rejected", "rejected"),
    )

    LANGUAGES = (
        ("english", "Inglés"),
        ("spanish", "Español"),
        ("portuguese", "Portugues"),
        ("english/spanish", "Inglés/Español"),
    )

    AUDIENCE_LEVEL = (
        ("beginner", "Beginner"),
        ("intermediate", "Intermediate"),
        ("advanced", "Advanced"),
        ("all", "All"),
    )

    name = models.CharField(max_length=200, default=None, blank=True, null=True)
    event = models.ForeignKey(
        "Event",
        related_name="talks",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        default=None,
    )
    status = models.CharField(max_length=20, choices=STATUS, default="draft")
    talk_type = models.CharField(
        max_length=30, choices=TALKS_TYPE, default=None, blank=True, null=True
    )
    audience_level = models.CharField(
        max_length=30, choices=AUDIENCE_LEVEL, default=None, blank=True, null=True
    )
    language = models.CharField(
        max_length=30, default=None, choices=LANGUAGES, blank=True, null=True
    )
    language_slider = models.CharField(
        max_length=30, default=None, choices=LANGUAGES, blank=True, null=True
    )
    duration = models.IntegerField(
        "Duration in minutes", default=0, blank=True, null=True
    )
    summary = models.TextField(default=None, blank=True, null=True)
    description = models.TextField(default=None, blank=True, null=True)
    topics = models.TextField(default=None, blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "talks"
        verbose_name = "Talk"
        verbose_name_plural = "talks"

    def __str__(self):
        if self.status != "published":
            return f"({self.status}) - {self.name}"
        return f"{self.name}"

    def is_keynote(self):
        return self.talk_type == "keynote"

    def is_workshop(self):
        return self.talk_type == "workshop"

    def registration_required(self):
        return self.talk_type in ["workshop", "sprints"]

    @property
    def published(self):
        return self.status == "published"

    def weight(self):
        weights = {
            "keynote": 50,
            "sprints": 30,
            "workshop": 20,
            "talk": 10,
        }
        return weights.get(self.talk_type, 0)

    def speakers(self):
        speakers = [
            spp.speaker.profile.full_name for spp in self.speakers_per_talk.all()
        ]
        return ", ".join(speakers)

pages/forms/talk_registration.py
from django import forms
from conferences.models.talks import Talk


class TalkRegistrationForm(forms.ModelForm):
    use_required_attribute = False

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

    class Meta:
        model = Talk
        fields = [
            "name",
            "event",
            "talk_type",
            "audience_level",
            "language",
            "language_slider",
            "summary",
            "topics",
            "description",
        ]
        required = [
            "name",
            "talk_type",
            "audience_level",
            "language",
            "language_slider",
            "summary",
            "topics",
            "description",
        ]
        labels = {
            "name": "Titulo de la propuesta",
            "talk_type": "Tipo",
            "summary": "Resumen / Abstract",
            "topics": "Palabras claves / Keywords",
            "description": "Descripcion Ampliada",
            "audience_level": "Nivel de audiencia",
            "language": "Idioma",
            "language_slider": "Idioma de las diapositivas",
        }

conferences/views/event_registrations.py
from rest_framework import viewsets
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter
from rest_framework import permissions
from conferences.models.event_registrations import EventRegistration
from conferences.serializers.event_registrations import EventRegistrationSerializer


class EventRegistrationViewSet(viewsets.ModelViewSet):
    queryset = EventRegistration.objects.all()
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    serializer_class = EventRegistrationSerializer

    def get_queryset(self):
        queryset = self.queryset
        return queryset

conferences/views/events.py
from rest_framework import viewsets
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter
from rest_framework import permissions
from conferences.models.events import Event
from conferences.serializers.events import EventSerializer


class EventViewSet(viewsets.ModelViewSet):
    queryset = Event.objects.all()
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    serializer_class = EventSerializer

    def get_queryset(self):
        queryset = self.queryset
        return queryset

conferences/views/talk_registration.py
from rest_framework import viewsets
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter
from rest_framework import permissions
from conferences.models.talk_registration import TalkRegistration
from conferences.serializers.talk_registration import TalkRegistrationSerializer


class TalkRegistrationViewSet(viewsets.ModelViewSet):
    queryset = TalkRegistration.objects.all()
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    serializer_class = TalkRegistrationSerializer

pages/templates/event/available-events.html
{% extends 'base.html' %}
{% load static %}

{% block body_content %}
{{ block.super }}
  <div class="container px-4 min-vh-100">
    {% for object in object_list %}
      <div class="mb-4">  
        <div class="flex mb-4">
          <div class="flex1 pt-4 pl-3">
            <div class="h1-border"></div>
          </div>
          <div class="px-3">
            <h1 class="border-0">{{ object.name }}</h1>
          </div>
          <div class="flex1 pt-4 pl-3">
            <div class="h1-border"></div>
          </div>
        </div>
        <div class="border-bottom mb-3 f7">
          {{ object.start_date }} / {{ object.end_date }}
        </div>
        <div class="mb-3">
          {% if object.description %}
          {{ object.description|format_as_md }}
          {% else %}
          No hay descripción disponible para este evento.
          {% endif %}
        </div>
        <div>
          {% if user.is_authenticated %}
            {% if object.registration_enabled %}
              <a class="btn btn-primary" href="{% url 'event_registration' object.id %}">Únete ahora</a>
            {% else %}
              <div class="alert alert-danger">
                El registro no está habilitado para este evento.
              </div>
            {% endif %}
            
          {% else %}
            <div class="alert alert-warning">
              Inicie sesión o regístrese para poder unirse a este evento.
            </div>
            <div class="text-center">
              <a class="btn btn-primary" href="{% url 'login' %}" class="">Iniciar sesión</a> ó
              <a class="btn btn-primary" href="{% url 'registration' %}" class="">Regístrarse</a>
            </div>
          {% endif %}
        </div>
      </div>
    {% endfor %}
  </div>

{% endblock %}

pages/templates/event/collaborator-profile.html
{% extends 'base.html' %}

{% block body_content %}
{{ block.super }}

<div class="container min-vh-100">
  <div class="row mt-4 mb-4 pb-4 mw7 mx-auto">
    <div class="text-center">
      {% if object.speaker.photo %}
      <img src="{{ speaker.photo.url }}" alt="" class="profile-photo-thumb">
      {% else %}
      <img src="/static/assets/images/perfil-hombre-default.jpg" alt="" class="profile-photo-thumb">
      {% endif %}
    </div>
    <div class="">
      <div class="h4 text-center mt-3">
        {{ object.full_name }}
      </div>
      <div class="h7 mb-3 em text-center">
        {% if object.job_title %}
          {{ speaker.profile.job_title }}
        {% endif %}
      </div>
      <div>
        {{ object.speaker.biography|format_as_md }}
      </div>
    </div>
  </div>
</div>
{% endblock %}

pages/templates/event/collaborators.html
{% extends 'base.html' %}

{% block body_content %}
{{ block.super }}

<div class="container px-4">
  <div class="flex mb-4">
    <div class="flex1 pt-4 pl-3">
      <div class="h1-border"></div>
    </div>
    <div class="px-3">
      <h1 class="border-0">{{ title }}</h1>
    </div>
    <div class="flex1 pt-4 pl-3">
      <div class="h1-border"></div>
    </div>
  </div>
</div>

<div class="container p-4 min-vh-100">
  <div class="row">
    {% for profile in profiles %}
      <div class="col-md-4 col-lg-3 pb-3">
        <div class="text-center">
          <a href="{% url 'collaborator_profile' profile.id %}">
            {% if profile.speaker.photo %}
            <img src="{{ profile.speaker.photo.url }}" alt="Foto de {{ profile.full_name }}" class="profile-photo-thumb">
            {% else %}
            <img src="/static/assets/images/perfil-hombre-default.jpg" alt="foto de {{ profile.full_name }}" class="profile-photo-thumb">
            {% endif %}
            <div class="h4 mt-3 red-wine">
              {{ profile.full_name }}
            </div>
            <div class="em">
              {% if profile.job_title %}
                {{ profile.job_title }}
              {% endif %}
            </div>
            <div class="black">
              {% if profile.country %}
                {{ profile.country }} 
              {% endif %}
            </div>
          </a>
        </div>
      </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

pages/templates/event/event-registration.html
{% extends 'base.html' %}
{% load static %}

{% block body_content %}
{{ block.super }}
  <div class="container min-vh-100">
    <div class="h3 pt-3 px-3">
      {{ object.name }} Registration
    </div>

    <div class="p-3">
      {{ object.description|format_as_md }}
    </div>

    <div class="p-3">
      <div class="alert alert-success">
        Felicidades ya estás registrado en el evento.
      </div>
    </div>
  </div>
{% endblock %}

pages/templates/event/event-talk-preview.html
{% extends 'base.html' %}
{% load event_talk_tags %}

{% block body_content %}
{{ block.super }}

{% if can_edit %}
<div class="container text-right">
  <a href="{% url 'talk_edit' talk.id %}" class="btn btn-primary">Modificar</a>
  <a href="{% url 'profile' %}" class="btn btn-secondary">Atras</a>
</div>
{% endif %}

<div class="container min-vh-100">
  {% talk_preview talk=talk hidden_resources=True %}

  <div class="h3">
    Recursos asociados
  </div>

  <div>
    <table class="table">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Tipo</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for resource in resources %}
        <tr>
          {% if resource.type == "ResourceLink" %}
            <td>
              <a href="{{ resource.url }}" target="_blank">{{ resource.title }}</a>
            </td>
            <td>
              Link
            </td>
          {% endif %}

          {% if resource.type == "ResourceFile" and resource.file %}
            <td>
              <a href="{{ resource.file.url }}" target="_blank">{{ resource.title }}</a>
            </td>
            <td>
              Archivo
            </td>
          {% endif %}

          {% if resource.type == "ResourceImage" and resource.photo %}
            <td>
              <a href="{{ resource.photo.url }}" target="_blank">{{ resource.title }}</a>
            </td>
            <td>
              Foto
            </td>
          {% endif %}
          <td class="text-end">
            <a href="{% url 'talk_resource_update' resource.id %}">Modificar</a>
            <a href="{% url 'talk_resource_delete' resource.id %}">Borrar</a>
          </td>
        </tr>
        {% endfor %}

        {% if resources.count == 0 %}
        <tr>
          <td colspan="3" class="text-center">No hay recursos cargados.</td>
        </tr>
        {% endif %}
      </tbody>
    </table>

    {% if can_edit %}
    <div class="my-3 text-center">
      <a href="{% url 'talk_resource_type' talk.id %}" class="btn btn-primary">Agregar recurso</a>
    </div>
    {% endif %}
  </div>
</div>




{% endblock %}

pages/templates/event/event-talk-registration-succesfull.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block body_content %}
{{ block.super }}
<div class="container min-vh-100">
  <div class="mt-3 mb-4">
    <h3>Propuesta Recibida.</h3>
  </div>

  <div class="alert alert-success">
    Muchas gracias su propuesta fue enviada para revision, le estaremos avisando.
  </div>

  <p>
    Ante cualquier duda o consulta puede enviarnos un mail a <a href="mailto:contacto@pythoncientifico.ar">contacto@pythoncientifico.ar</a>
  </p>
</div>
{% endblock %}

pages/templates/event/event-talk-registration.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block body_content %}
{{ block.super }}

<div class="container flex mb-4">
  <div class="flex1 pt-4 pl-3">
    <div class="h1-border"></div>
  </div>
  <div class="px-3">
    <h1 class="border-0">{{event.name}}</h1>
  </div>
  <div class="flex1 pt-4 pl-3">
    <div class="h1-border"></div>
  </div>
</div>

<div class="container mw7 mx-auto mb-3">
  <div class="mt-3">
    {% if edition %}
    <h3>Actualizar Propuestas</h3>
    {% else %}
    <h3>Envio de Propuestas</h3>
    {% endif %}
  </div>

  {% if event.call_for_papers_page %}
  <div class="mb-3">
    <span class="bold">¿No tenes ídea de como enviar una propuesta?</span> <br>
    te adjuntamos una <a href="{% url 'static_page' event.call_for_papers_page.slug %}">guía de presentación de propuestas.</a>
  </div>
  {% endif %}

  <div class="">
    <form method="post">
      {% csrf_token %}

      {{ form|crispy }}

      <div class="form-group mt-4">
        <input type="submit"  value="Guardar" class="btn btn-primary w-100" />
      </div>
    </form>
  </div>
</div>
{% endblock %}

pages/templates/event/event-talk-resource-create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body_content %}
{{ block.super }}

<div class="container min-vh-100">
  <div class="mw6 mx-auto mb-3">
    <div class="text-center">
      <h1>{{ talk.name }}</h1>
      <h4>Agregar recurso</h4>
    </div>

    <div class="">
      <form method="post">
        {% csrf_token %}
        <div class="px-3 py-3">
        {{ form|crispy }}
        </div>
        <div class="form-group mt-4">
          <input type="submit"  value="Siguiente" class="btn btn-primary w-100" />
        </div>
        <div class="mt-3">
          <a href="{% url 'talk_preview' talk.id %}" class="btn btn-secondary w-100">Atras</a>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

pages/templates/event/event-talk-resource-delete.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block body_content %}
{{ block.super }}


<form method="post">{% csrf_token %}
     
  <div class="container min-vh-100">  
    <div class="mw6 mx-auto mb-3">
      <div class="text-center">
        <h3>Eliminar recurso</h3>
      </div>

      <div class="">
        <form method="post">
          {% csrf_token %}

          ¿Estas seguro que deseas eliminar el recurso <strong>{{ object.type }}: {{ object.title }}</strong>?
  
          <div class="form-group mt-4">
            <input type="submit"  value="Borrar" class="btn btn-primary w-100" />
          </div>
          <div class="mt-3">
            <a href="{% url 'talk_preview' talk.id %}" class="btn btn-secondary w-100">Atras</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

pages/templates/event/event-talk-resource-form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block body_content %}
{{ block.super }}

<div class="container min-vh-100">
  <div class="text-center">
    <h1>{{ talk.name }}</h1>
    <h3>Agregar {{ resource_type }}</h3>
  </div>

  <div class="mw6 mx-auto mb-3">
    <div class="">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form|crispy }}

        <div class="form-group mt-4">
          <input type="submit"  value="Guardar" class="btn btn-primary w-100" />
        </div>
        <div class="mt-3">
          <a href="{% url 'talk_preview' talk.id %}" class="btn btn-secondary w-100">Atras</a>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

pages/templates/event/talk-registration.html
{% extends 'base.html' %}
{% load static %}


{% block body_content %}
{{ block.super }}
  <div class="container px-4 min-vh-100">
    <div class="row">
      <div class="col-md-9">
        <h3>Inscripción a  Workshop/Taller/Sprints</h3>
      </div>
      <div class="col-md-3 text-end">
        <a class="btn btn-secondary" href="{% url 'profile' %}">volver a perfil</a>
      </div>
    </div>

    <div class="row">
      <table class="table w-100">
        <thead>
          <tr>
            <th>Evento</th>
            <th>Taller</th>
            <th>Tipo</th>
            <th>Audiencia</th>
            <th>Duración</th>
            <th>Idioma</th>

            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for talk in talleres %}
            {% if talk.id not  in  inscripciones %}
              <tr>
            {% else %}
                <tr bgcolor=#EAFAF1>
            {% endif %}
              <td> {{ talk.event.name }} </td>
              <td> {{ talk }} </td>
              <td> {{ talk.get_talk_type_display }} </td>
              <td> {{ talk.audience_level }} </td>
              <td> {{ talk.duration }} </td>
              <td> {{ talk.get_language_display }} </td>
              <td>
                {% if talk.id not  in  inscripciones %}
                  <a href="{% url 'talk-registration-add' talk.id %}">Inscribir</a>
                {% else %}
                    <a href="{% url 'talk-registration-del' talk.id %}">Anular</a>
                {% endif %}
              </td>
            </tr>
          {% endfor %}

          {% if not talleres|length %}
            <tr>
              <td colspan="5"> No hay Workshop/Taller/Sprints habilitados todavía. </td>
            </tr>
          {% endif %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}